create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  guild_id text,
  channel_id text not null,
  url text not null,
  name text,
  is_active boolean not null default true,
  last_post_id text,
  last_post_signature text,
  created_at timestamptz not null default now()
);

alter table public.sources enable row level security;

create index if not exists sources_active_idx on public.sources (is_active);
create index if not exists sources_url_idx on public.sources (url);

comment on table public.sources is
  'Private server-side subscription source table for Muel bot monitors. Access through service role only.';
